apiVersion: apps/v1
kind: Deployment
metadata:
  name: than
spec:
  replicas: 1
  selector:
    matchLabels:
      app: than
  template:
    metadata:
      labels:
        app: than
    spec:
      containers:
      - image: okteto.dev/than:latest
        name: than
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "23f50ba2-6f11-44fd-8828-7b0bc7454147"
        - name: Vless_Path
          value: "/6475udjeu457d4i5ry"
        - name: Vmess_UUID
          value: "23f50ba2-6f11-44fd-8828-7b0bc7454147"
        - name: Vmess_Path
          value: "/6475udjeu457d4i5ry"
        - name: Share_Path
          value: "/v2link"
